### ISSUE TITLE
Add support for scope parameter

### ISSUE THREAD

**Issue by elazar** [Invoiced/oauth1-xero#3]
Per the [Xero documentation](https://developer.xero.com/documentation/payroll-api-us/overview-payroll-us#permissions), the `scope` parameter is used to request access to non-accounting endpoints:

> By default all API applications have access to the accounting endpoints only... With public and partner applications you need to specify the “scope” parameter when you redirect the user to the Authorise screen in Xero to request sufficient privileges.

The `Xero` class in this repository doesn't currently support this parameter. If you can provide guidance on how you prefer for it to be implemented, I'd be happy to submit a pull request to add this support.

**Comment by jaredtking** [comment]
Since the `scope` parameter is added on to the URL as a query parameter you could extend the `Xero` class and override the `urlAuthorization()` method to include your custom scope. What are your thoughts?

**Comment by elazar** [comment]
Or just handle it from the class using a `Xero` instance, sure. I just thought including something like a `setScope()` method in the `Xero` class would be a bit nicer.

**Comment by elazar** [comment]
A good example of where this has been implemented is in the `Trello` class that's part of `league/oauth1-client`. Its `urlAuthorization()` method [calls](https://github.com/thephpleague/oauth1-client/blob/7523d2aedceabe8ee2d9ab56cd1ff5ec67fbc676/src/Client/Server/Trello.php#L156) a [separate method](https://github.com/thephpleague/oauth1-client/blob/7523d2aedceabe8ee2d9ab56cd1ff5ec67fbc676/src/Client/Server/Trello.php#L220) that handles creating the query string, which includes a scope parameter.

**Comment by jaredtking** [comment]
I agree that a `setScope()` method would be useful here. If you want to submit a PR with that change I would merge it.
