### ISSUE TITLE
error 52: Empty reply from server (Partner App)

### ISSUE THREAD

**Issue by judgej** [Invoiced/oauth1-xero#5]
I have set up credentials and certs for a Partner app, and get the following error when trying to get the temporary credentials (`$server->getTemporaryCredentials()`)

```text
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186 Stack trace:
#0 /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /.../vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) in /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
```

Tried this with the Twitter provider, and that works fine straight away.

What I don't know is what this package was requesting to get no response. I cannot find any details on what circumstances Xero would not return a response, so I have no idea what credentials may be missing or incorrect (I've copied them all in from another application that is working under a different library). Catching the Guzzle exception and extracting the response from that gives me a null - Guzzle literally has no response to give me.

I guess the answer is buried under layers  of factories and classes, but do you have any idea how I would get to it? If this is a problem with missing credentials, then would additional validation to catch that make sense? Or perhaps it is just *wrong* credentials?

The exception is raised immediately - it does not appear to be waiting any time on a timeout.

I'll try out private and public apps to see if there are any further clues. I'm wondering whether the Partner app is just more reluctant to return reasons for failure, as a security feature.

**Comment by jaredtking** [comment]
`$server->getTemporaryCredentials()` will call the Xero API at either https://api-partner.network.xero.com/oauth/RequestToken (partner apps) or https://api.xero.com/oauth/RequestToken (non-partner apps). You can see where this happens in the [Xero class](https://github.com/Invoiced/oauth1-xero/blob/master/src/Xero.php#L104).

If you are getting an empty response then I would make sure you have configured both the client credentials and RSA key correctly. Also, keep in mind that Xero has [deprecated Entrust certificates](https://developer.xero.com/documentation/auth-and-limits/entrust-certificate-deprecation). I'm going to update the partner instructions to reflect this.

**Comment by jaredtking** [comment]
Check out the [updated partner app instructions](https://github.com/Invoiced/oauth1-xero#partner-api). Does that help?

**Comment by judgej** [comment]
Hmm, just commenting out the `'partner' => true,` parameter is enough to get the partner app to work. The "empty response" exception disappears together.

I can remove the entrust certs and it still works.

Why would `partner` being true have such a devastating effect? Is that because it uses different endpoints that are no longer supported?

**Comment by jaredtking** [comment]
Most likely because it uses api-partner.network.xero.com instead of api.xero.com. Going forward they recommend using api.xero.com so you can safely remove the partner and Entrust configuration options.

**Comment by judgej** [comment]
I'm happy this fixes my problem, so this issue can be closed from my POV (you may have some endpoints to update, I'm not sure). Thanks.

**Comment by jaredtking** [comment]
Version 1.1 of the library should already have the correct endpoints. I'll go ahead and close this. Thanks!
