### ISSUE TITLE
Refresh token and expiry time

### ISSUE THREAD

**Issue by judgej** [Invoiced/oauth1-xero#6]
The Partner app expires its tokens at regular intervals and they need to be renewed. To do that, two things are needed as a part of the final credentials:

* Expiry time or period (`oauth_expires_in` in the OAuth response).
* The refresh token (`oauth_session_handle` in the OAuth response).

This package provides the `identifier` (aka `oauth_token`) and `secret` (aka `oauth_token_secret`) only after authorisation. Is the expiry and refresh token available anywhere?

The underlying PHP League OAuth 1.x package does not seem to make any reference to these two credential values, but I guess they can be pulled out from *somewhere*?

Without these, a Partner app cannot run unattended.

**Comment by jaredtking** [comment]
You can actually get the refresh token info from the underlying client. Here's how we do it:
```php
$data = $server->getLastTokenCredentialsResponse();
$expiresIn = $data['oauth_expires_in'];
$sessionHandle = $data['oauth_session_handle'];
$sessionExpiresIn = $data['oauth_authorization_expires_in'];
```

**Comment by judgej** [comment]
Just realised also in Step 3, immediately after getting the credentials from the temporary credentials (`$server->getTokenCredentials()`), you can get the remainder of the credentials using `$server->getLastTokenCredentialsResponse()`:

```php
array(6) {
  ["oauth_token"]=>
  string(30) "RX3RNJIFAAS9S...WJOKLRTN"
  ["oauth_token_secret"]=>
  string(30) "QABOQETWUS1...Q93HMEI3"
  ["oauth_expires_in"]=>
  string(4) "1800"
  ["oauth_session_handle"]=>
  string(20) "4XHE6Y...QPFQEU"
  ["oauth_authorization_expires_in"]=>
  string(9) "315360000"
  ["xero_org_muid"]=>
  string(22) "kIYur4ajkq...hzRFm"
}
```

In case you were wondering, 315360000 seconds is ten years!

**Comment by jaredtking** [comment]
Exactly. The access token can be refreshed using the session handle (refresh token) far into the future. Should I go ahead and close this issue?

**Comment by judgej** [comment]
Sorry - I let this one slip by without closing, Thanks.
